server:
  port: 8082


spring:
  datasource:
    url: jdbc:mysql://49.232.1.117:3306/cloudplatform?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf8&useSSL=false&allowMultiQueries=true
    username: hanhan
    password: HanHan_1024
    driver-class-name: com.mysql.cj.jdbc.Driver
  thymeleaf:
    cache: false
  mvc:
    servlet:
      path: /